#!/bin/bash

# файл для отправки
file_path="/home/ubuntu/testfile"
# адрес получателя
receiver_host="34.220.97.124" 
receiver_user="ubuntu" # пользователь на удаленном хосте 
log_file="/home/ubuntu/logfile.log" # файл с результатом проверки размера файла (отправленный = полученный)

# архивирование файла
archive_name="$(basename ${file_path}).tar.gz"
tar -zcf "$archive_name" "$file_path"

# Отправка файла на удаленный сервер
scp "$archive_name" "$receiver_user@$receiver_host:/home/ubuntu/$archive_name" >> $log_file

# Получение размера файла в байтах
file_size=$(stat -c%s "$archive_name")

# Отправка команды на удаленный сервер для проверки файла и ожидание подтверждения
ssh -T $receiver_user@$receiver_host << EOF | grep -E "File received successfully\. Size match\.|File size doesn't match\. Something went wrong\." >> $log_file
received_file_size=\$(stat -c%s "/home/ubuntu/$archive_name")

if [ \$received_file_size -eq $file_size ]; then
  echo "File received successfully. Size match."
else
  echo "File size doesn't match. Something went wrong."
fi
EOF

# удаление архива после отправки, если файлы совпали
if [ $? -eq 0 ]; then
  rm -f $archive_name
fi
